### PR TITLE
Doc: Add Installation instructions using Pip

### PR DESCRIPTION
**Pull request by vkartik97**
Added instructions for installation using `pip install evalai`.

### CODE REVIEW

**Comment by vkartik97** [comment]
@deshraj  @RishabhJain2018 The build fails on even master branch 
Screenshot from 2019-07-09 01-09-45

**Comment by deshraj** [comment]
@vkartik97 can you please fix it and add a PR for that?

**Comment by vkartik97** [comment]
@deshraj On it : )
This issue is creating kind of confusion, [build is passing](https://travis-ci.org/Cloud-CV/evalai-cli/builds/541886644?utm_source=github_status&utm_medium=notification) on latest commit on master branch, but when we run the build again, it fails.

**Comment by vkartik97** [comment]
Build fail issue resolved in https://github.com/Cloud-CV/evalai-cli/pull/168

**Pull request merged**
