### PR TITLE
Add some features on the docs page

### PR DESCRIPTION
**Pull request by gautamjajoo**
- [x] Added scroll to top feature when scrolled after 100px
- [x] Added smooth scroll to `See-examples` button
- [x] Changes done in the footer
- [x] Changed text-color when hovered on `See-examples` button according to UI.
- [x] Update ReadME with description about the project
@RishabhJain2018 

capture

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@gautamjajoo Everything looks good except 
screenshot 2019-02-11 at 2 46 40 pm
Also, please resolve the conflicts.

**Comment by gautamjajoo** [comment]
@RishabhJain2018 I haven't linked `font-awesome` yet. Because #133 already does that. Should I add in this PR itself?

**Comment by RishabhJain2018** [comment]
I see..it makes sense. Can you please resolve the conflicts?

**Comment by gautamjajoo** [comment]
Please do not review this. Something is messed up, will do the changes till tomorrow!

**Comment by gautamjajoo** [comment]
Opened https://github.com/Cloud-CV/evalai-cli/pull/143.

**Pull request closed without merging**
