### PR TITLE
Phases formatting fix.

### PR DESCRIPTION
**Pull request by isht3**

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@isht3 please add the screenshot here.

**Comment by isht3** [comment]
@RishabhJain2018 Added

**Comment by RishabhJain2018** [comment]
@isht3 Please see to it as it looks ugly
screen shot 2018-07-05 at 3 44 52 pm

**Comment by isht3** [comment]
That's because of the size of the table is bigger than your terminal. Should I reduce it?

**Comment by isht3** [comment]
@RishabhJain2018 Fixed. Can you check again?

**Comment by RishabhJain2018** [comment]
Nopes @isht3 
Please see the screenshot 
screen shot 2018-07-06 at 3 49 17 pm

**Comment by isht3** [comment]
@RishabhJain2018 I think this oughta fix it. Can you check?

**Pull request merged**
