### PR TITLE
[WIP] Docs - Installation and instruction.

### PR DESCRIPTION
**Pull request by isht3**

### CODE REVIEW

**Comment by deshraj** [comment]
@isht3 can you please add the command on how to build the docs on the local machine?

**Comment by deshraj** [comment]
Also, please add the screenshots of the docs page.

**Comment by isht3** [comment]
@deshraj  I've added the README for building the docs.

**Comment by deshraj** [comment]
Oh I see but there are some of the changes that you need to do to get it to work:

1. Add the command `cd docs/`
2. Update the requirements file with sphinx and other required packages

**Pull request closed without merging**
