### PR TITLE
EvalAi CLI ASCII Logo

### PR DESCRIPTION
**Pull request by adityaputravu**
I have added the CLI ASCII logo to the main.py which I have designed

### CODE REVIEW

**Comment by vkartik97** [comment]
@adityaputravu 
Looks good to me!
@RishabhJain2018  @deshraj  Please review

**Comment by RishabhJain2018** [comment]
@adityaputravu Can you please paste the screenshot too. Thanks.

**Comment by adityaputravu** [comment]
screen shot 2018-10-30 at 16 54 41

@RishabhJain2018

**Comment by deshraj** [comment]
Thanks @adityaputravu. Can you please capitalize last `I` ?

**Comment by deshraj** [comment]
Also, is it possible to build this whole logo using one character such as `#` ?

Thanks

**Comment by adityaputravu** [comment]
screen shot 2018-10-30 at 19 39 58
@deshraj

**Comment by isht3** [comment]
@adityaputravu This looks much better! LGTM

**Comment by deshraj** [comment]
Thanks @adityaputravu. @isht3 can you please merge this ?

**Comment by isht3** [comment]
@deshraj Done. :+1:

**Pull request merged**
