### PR TITLE
Set token through CLI

### PR DESCRIPTION
**Pull request by sayamkanwar**
I have added the functionality to add or set token through CLI by running `evalai token [TOKEN]`. It saves the token to token.json file.

demo new

Please review this @RishabhJain2018 @vkartik97

### CODE REVIEW

**Comment by sayamkanwar** [comment]
@vkartik97 
Made the necessary changes, it's working now!

**Comment by sayamkanwar** [comment]
@vkartik97 Made the change you asked for! Please have a look at it now and let me know if any more changes are required.

**Comment by vkartik97** [comment]
LGTM :+1:
@deshraj  @RishabhJain2018   Please review

**Comment by sayamkanwar** [comment]
@Ram81 @RishabhJain2018 @deshraj Please review it so that I can proceed further

**Comment by RishabhJain2018** [comment]
Closing this since @C0derLint has already fixed it. Thanks @sayamkanwar for the effort though.

**Pull request closed without merging**
