### PR TITLE
Create a separate requirements file for production

### PR DESCRIPTION
**Pull request by itaisteinherz**
I've split up the current `requirements.txt` file into two separate requirements files - `requirements-prod.txt` for production and `requirements-dev.txt` for development.

// cc @RishabhJain2018 @vkartik97

### CODE REVIEW

**Comment by itaisteinherz** [comment]
@vkartik97 Done in e6432789f9fefcefa16af41ff2bc28f0007efa4c.

**Comment by itaisteinherz** [comment]
@vkartik97 Done in 28f6211ec8dfaef68aca00b849e9f7da01ea5ff4 (I forgot to update the Travis config, and so I fixed it in 39b1a4439fe7fc9f35cabb7ad20d7f7339bebb2e).

**Comment by vkartik97** [comment]
@itaisteinherz 
Last Change:  Add `python-dateutil` to `requirements.txt`.

**Comment by itaisteinherz** [comment]
> Add `python-dateutil` to `requirements.txt`.

I removed it because it's only used in the tests. I can add it back but since it isn't used in any of the production code, there's no reason for it to be installed in production.

**Comment by vkartik97** [comment]
>I removed it because it's only used in the tests.

Can you check if the CLI(commands like `challenges`) is working fine with dependencies in `requirements.txt`?

**Comment by vkartik97** [comment]
@itaisteinherz 
`python-dateutil==2.7.3` is used by `evalai/utils/common.py` :  [#L6](https://github.com/Cloud-CV/evalai-cli/blob/a9427862f53103a16e9921533ae94dcde678dfad/evalai/utils/common.py#L6) and [#L7](https://github.com/Cloud-CV/evalai-cli/blob/a9427862f53103a16e9921533ae94dcde678dfad/evalai/utils/common.py#L7)

**Comment by itaisteinherz** [comment]
@vkartik97 @RishabhJain2018 Is this or #111 going to get merged? The other PR seems to be of similar intentions, and I'd like to know which one is being accepted into the project.

// cc @vpn1997 @techytushar

**Comment by itaisteinherz** [comment]
Any updates? @vkartik97 @vpn1997

**Comment by RishabhJain2018** [comment]
Hi @itaisteinherz Thanks for the effort but it seems that #111 is opened before this one, so we'll accept that PR :). Hence, closing this!

**Pull request closed without merging**
