### PR TITLE
Add documentation for large submission command and private submission

### PR DESCRIPTION
**Pull request by Ram81**
### Description

This PR adds:
- [x] Documentation for large submission upload command
- [x] Documentation for public/private submission for prediction upload challenge
- [x] Documentation for public/private submission for code upload challenge
- [x] Documentation for annotation upload

### CODE REVIEW

**Review by RishabhJain2018 — CHANGES_REQUESTED** [review]
@Ram81 Can you please paste the screenshot of the page.

**Comment by Ram81** [comment]
Screen Shot 2020-11-10 at 10 22 18 PM
2.12 PM.png…]()

Screen Shot 2020-11-10 at 10 22 12 PM

**Review by RishabhJain2018 — APPROVED** [review]

**Review by RishabhJain2018 — CHANGES_REQUESTED** [review]
Can we please add the documentation for the large annotation files as well.

**Comment by Ram81** [comment]
Screen Shot 2020-11-11 at 7 42 40 PM

**Review by RishabhJain2018 — APPROVED** [review]

**Pull request merged**
